name: Build and Test
run-name: Build and Test [${{ github.actor }}]
on: [push]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Install GCC
            uses: egor-tensin/setup-gcc@v1.3
            with:
                version: '13'
                platform: x64
          - name: Install Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"
          - name: Install python dependencies
            run: |
              python -m pip install --upgrade pip
              pip install requests
          - name: Install TBB
            run: sudo apt install libtbb-dev
          - name: Install xmake
            run: |
                sudo add-apt-repository ppa:xmake-io/xmake
                sudo apt update
                sudo apt install xmake
                xmake f --cc=$(which gcc) --cxx=$(which g++) --ld=$(which g++)
          - name: Compile Coffeedb
            run: xmake -rv
          - name: Start Coffeedb
            run: nohup build/linux/x86_64/release/coffeedb &
          - name: Test
            run: |
              python examples/example.py
              python test/test-string.py
          
            
          
