name: Build and Test
run-name: Build and Test [${{ github.actor }}]
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Install GCC
            uses: egor-tensin/setup-gcc@v1.3
            with:
                version: '13'
                platform: x64
          - name: Install Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"
          - name: Install xmake
            run: |
                sudo add-apt-repository ppa:xmake-io/xmake
                sudo apt update
                sudo apt install xmake
                pwd
                gcc -v
                which gcc
                sudo rm /usr/bin/gcc
                sudo ln -s /usr/local/bin/gcc /usr/bin/gcc
          - name: Compile Coffeedb
            run: xmake -rv
          - name: Start Coffeedb
            run: nohup build/linux/x86_64/release/coffeedb &
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - run: python examples/example.py
          
            
          
